CREATE TABLE [dbo].[APEs]
(
	[Id] BIGINT NOT NULL IDENTITY,
	[PatientId] BIGINT NULL,
	[PatientRegistrationId] BIGINT NULL,
    [DateInputted] DATETIME NULL,
    [PatientName] NVARCHAR(200) NOT NULL,
    [CompanyName] NVARCHAR(200) NULL, 
    [DepartmentOrAgency] NVARCHAR(100) NULL, 
    [Age] NVARCHAR(50) NULL, 
    [BirthDate] DATETIME NULL, 
    [Gender] NVARCHAR(10) NULL, 
    [CivilStatus] NVARCHAR(50) NULL, 
    [ContactNo] NVARCHAR(100) NULL,
    [ENT] NVARCHAR(200) NULL,
    [Gastroenterology] NVARCHAR(200) NULL,
    [Respiratory] NVARCHAR(200) NULL,
    [IntegumentarySkin] NVARCHAR(200) NULL,
    [Cardiology] NVARCHAR(200) NULL,
    [Psychology] NVARCHAR(200) NULL,
    [Endocrinology] NVARCHAR(200) NULL,
    [OBGyneUrology] NVARCHAR(200) NULL,
    [Muscoloskeletal] NVARCHAR(200) NULL,
    [InfectiousCommunicable] NVARCHAR(200) NULL,
    [Neurological] NVARCHAR(200) NULL,
    [Surgical] NVARCHAR(200) NULL,
    [OthersPast] NVARCHAR(200) NULL,
    [Medications] NVARCHAR(200) NULL,
    [ReviewOfSystems] NVARCHAR(200) NULL,
    [Allergies] NVARCHAR(200) NULL,
    [IsSmoking] BIT NULL, 
    [SmokingSinceWhen] NVARCHAR(200) NULL,
    [NumberOfSticksPerDay] INT NULL, 
    [IsDrinking] BIT NULL, 
    [DrinkingSinceWhen] NVARCHAR(200) NULL,
    [NumberOfBottles] INT NULL, 
    [DrinkingFrequency] NVARCHAR(20) NULL, 
    [LMP] NVARCHAR(50) NULL, 
    [LMPType] NVARCHAR(50) NOT NULL DEFAULT '', 
    [BP1st] NVARCHAR(20) NULL, 
    [BP2nd] NVARCHAR(20) NULL, 
    [CardiacRate1st] NVARCHAR(20) NULL, 
    [CardiacRate2nd] NVARCHAR(20) NULL, 
    [Height] NVARCHAR(20) NULL, 
    [Weight] NVARCHAR(20) NULL, 
    [BMICategory] NVARCHAR(50) NULL, 
    [VARightEyeWGlasses] NVARCHAR(50) NULL, 
    [VARightEyeWOGlasses] NVARCHAR(50) NULL, 
    [VALeftEyeWGlasses] NVARCHAR(50) NULL, 
    [VALeftEyeWOGlasses] NVARCHAR(50) NULL, 
    [VisualAcuity] NVARCHAR(20) NULL, 
    [Skin] NCHAR(2) NULL,
    [HeadScalp] NCHAR(2) NULL,
    [Eyes] NCHAR(2) NULL,
    [Ears] NCHAR(2) NULL,
    [Nose] NCHAR(2) NULL,
    [TeethTonsilsThroatPharynx] NCHAR(2) NULL,
    [NeckLymphNodesThyroid] NCHAR(2) NULL,
    [ThoraxBreast] NCHAR(2) NULL,
    [HeartLungs] NCHAR(2) NULL,
    [AbdomenLiverSpleen] NCHAR(2) NULL,
    [InguinalAreaGenitalsAnus] NCHAR(2) NULL,
    [ExtremetiesSpine] NCHAR(2) NULL,
    [Tattoo] NCHAR(2) NULL,
    [MassCyst] NCHAR(2) NULL,
    [OthersPE] NCHAR(2) NULL,
    [Findings] NVARCHAR(500) NULL, 
    [VitalSignsBy] NVARCHAR(50) NOT NULL DEFAULT '', 
    [HeightWeightBy] NVARCHAR(50) NOT NULL DEFAULT '',
    [IsActive] BIT NOT NULL DEFAULT 1, 
    [CreatedByUserId] BIGINT NOT NULL DEFAULT 0,
    [CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
    [UpdatedByUserId] BIGINT NOT NULL DEFAULT 0,
    [UpdatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [APE_Id] PRIMARY KEY CLUSTERED 
    (
	    [Id] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
