CREATE TABLE [dbo].[CompanySetups]
(
	[Id] BIGINT NOT NULL IDENTITY,
    [CompanyName] NVARCHAR(200) NULL,
    [SubCompanyName] NVARCHAR(200) NULL,
    [Tagline] NVARCHAR(500) NULL,
    [Address] NVARCHAR(200) NULL,
    [ContactNumbers] NVARCHAR(200) NULL,
    [Email] NVARCHAR(200) NULL,
    [Code] NVARCHAR(20) NULL,
    [Logo] VARBINARY(MAX) NULL,
    [UpdatedByUserId] BIGINT NOT NULL DEFAULT 0,
    [UpdatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [CompanySetup_Id] PRIMARY KEY CLUSTERED 
    (
	    [Id] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
)
