CREATE TABLE [dbo].[Companies]
(
	[Id] BIGINT NOT NULL IDENTITY,
    [CompanyName] NVARCHAR(200) NOT NULL,
    [Address] NVARCHAR(500) NOT NULL,
    [ContactNumbers] NVARCHAR(200) NOT NULL,
    [ContactPerson] NVARCHAR(200) NOT NULL,
    [IsActive] BIT NOT NULL DEFAULT 1, 
    [CreatedByUserId] BIGINT NOT NULL DEFAULT 0,
    [CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
    [UpdatedByUserId] BIGINT NOT NULL DEFAULT 0,
    [UpdatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [Company_Id] PRIMARY KEY CLUSTERED 
    (
	    [Id] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
