CREATE TABLE [dbo].[Hematologies]
(
	[Id] BIGINT NOT NULL IDENTITY,
    [PatientId] BIGINT NULL,
	[PatientRegistrationId] BIGINT NULL,
    [PatientCode] NVARCHAR(200) NOT NULL,
    [PatientName] NVARCHAR(200) NOT NULL,
    [CompanyOrPhysician] NVARCHAR(200) NOT NULL,
    [Age] NVARCHAR(50) NULL,
    [Sex] NVARCHAR(20) NULL,
    [DateRequested] DATETIME NULL,
    [Photo] VARBINARY(MAX) NULL,
    [HematocritNValue] NVARCHAR(100) NULL,
    [HematocritResult] NVARCHAR(100) NULL,
    [HemoglobinNValue] NVARCHAR(100) NULL,
    [HemoglobinResult] NVARCHAR(100) NULL,
    [WBCCountNValue] NVARCHAR(100) NULL,
    [WBCCountResult] NVARCHAR(100) NULL,
    [SegmentersNValue] NVARCHAR(100) NULL,
    [SegmentersResult] NVARCHAR(100) NULL,
    [LymphocytesNValue] NVARCHAR(100) NULL,
    [LymphocytesResult] NVARCHAR(100) NULL,
    [EosinophilsNValue] NVARCHAR(100) NULL,
    [EosinophilsResult] NVARCHAR(100) NULL,
    [MonocytesNValue] NVARCHAR(100) NULL,
    [MonocytesResult] NVARCHAR(100) NULL,
    [BasophilsNValue] NVARCHAR(100) NULL,
    [BasophilsResult] NVARCHAR(100) NULL,
    [StabNValue] NVARCHAR(100) NULL,
    [StabResult] NVARCHAR(100) NULL,
    [PlateletCountNValue] NVARCHAR(100) NULL,
    [PlateletCountResult] NVARCHAR(100) NULL,
    [Remarks] NVARCHAR(100) NULL,
    [MedicalTechnologist] NVARCHAR(100) NOT NULL,
    [Pathologist] NVARCHAR(100) NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT 1, 
    [CreatedByUserId] BIGINT NOT NULL DEFAULT 0,
    [CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
    [UpdatedByUserId] BIGINT NOT NULL DEFAULT 0,
    [UpdatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [Hematology_Id] PRIMARY KEY CLUSTERED 
    (
	    [Id] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
