CREATE TABLE [dbo].[MultiLineEntries]
(
	[Id] BIGINT NOT NULL IDENTITY, 
    [ModuleId] INT NULL, 
    [FieldName] VARCHAR(50) NOT NULL, 
    [FieldValueTitle] VARCHAR(100) NOT NULL,
    [FieldValue] VARCHAR(MAX) NOT NULL,
    [IsActive] BIT NOT NULL DEFAULT 1, 
    [CreatedByUserId] BIGINT NOT NULL DEFAULT 0,
    [CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
    [UpdatedByUserId] BIGINT NOT NULL DEFAULT 0,
    [UpdatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [MultiLineEntry_Id] PRIMARY KEY CLUSTERED 
    (
	    [Id] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
    CONSTRAINT [FK_MultiLineEntry_Modules] FOREIGN KEY ([ModuleId]) REFERENCES [Modules]([Id])
)
