CREATE TABLE [dbo].[Patients]
(
	[Id] BIGINT NOT NULL IDENTITY,
    [PatientName] NVARCHAR(200) NOT NULL,
    [DateOfBirth] DATETIME NULL,
    [Age] NVARCHAR(50) NULL,
    [Gender] NVARCHAR(20) NULL,
    [CivilStatus] NVARCHAR(20) NULL,
    [Address] NVARCHAR(500) NOT NULL,
    [ContactNumbers] NVARCHAR(50) NULL,
	[CompanyId] BIGINT NULL DEFAULT 0,
    [IsActive] BIT NOT NULL DEFAULT 1, 
    [CreatedByUserId] BIGINT NOT NULL DEFAULT 0,
    [CreatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
    [UpdatedByUserId] BIGINT NOT NULL DEFAULT 0,
    [UpdatedDate] DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [Patient_Id] PRIMARY KEY CLUSTERED 
    (
	    [Id] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
    CONSTRAINT [FK_Patient_Companies] FOREIGN KEY ([CompanyId]) REFERENCES [Companies]([Id])
)
